include:
  # https://gitlab.com/gitlab-org/gitlab/-/tree/master/lib/gitlab/ci/templates/Security
  # https://docs.gitlab.com/ee/ci/testing/code_quality.html
  - template: Code-Quality.gitlab-ci.yml
    # https://docs.gitlab.com/ee/user/application_security/sast/
  - template: Security/SAST.gitlab-ci.yml
    # https://docs.gitlab.com/ee/user/application_security/secret_detection/
  - template: Security/Secret-Detection.gitlab-ci.yml
    # https://docs.gitlab.com/ee/user/application_security/iac_scanning/
  - template: Security/SAST-IaC.gitlab-ci.yml
variables:
  DS_MAX_DEPTH: 10
  CODE_QUALITY_DISABLED: false
  GIT_DEPTH: 10
  SECURE_LOG_LEVEL: debug
  VITE_DATABASE_URL: 'https://siouoxdqpgykibzayejt.supabase.co'
  VITE_DATABASE_KEY: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNpb3VveGRxcGd5a2liemF5ZWp0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY0NzIxODIsImV4cCI6MjA3MjA0ODE4Mn0.sgavqOdB1sjrNpQdvdC4669xTtwPQoRACo53Tn13pZk'
  VITE_REQUIREMENTS_URL: '/krav.json'
  VITE_PREFILL_REQUIREMENTS: '[{"id":"1","automatic":"false","activateText":"Granskningsobjektet använder enbart designsystemets komponenter","status":"IRRELEVANT","requirements":"35,42,43,44,45,46","comment":"Detta krav har förifyllts som irrelevant eftersom granskningsobjektet använder enbart designsystemets komponenter."},{"id":"2","automatic":"true","activateText":"","status":"IRRELEVANT","requirements":"128,129,130,131,131,132","comment":"Arbetsförmedlingen har beslutat att krav rörande support och dokumentation faller utanför ansvarsområdet för detta granskningsobjekt."}]'

secret_evaluation:
  needs: [secret_detection]
  artifacts:
    paths:
      - gl-secret-detection-report.json
  stage: test
  image: alpine:latest
  before_script:
    - apk add --no-cache jq
  script:
    - |
      if [ -f "gl-secret-detection-report.json" ]; then
        if [ "$(jq '.vulnerabilities | length' gl-secret-detection-report.json)" -gt 0 ]; then
          echo "🚨 Secrets detected! Failing the job."
          exit 1
        else
          echo "✅ No secrets found."
        fi
      else
        echo "⚠️ Report file missing. Evaluation skipped."
      fi

pages:
  image: node:22
  stage: deploy
  script:
    - npm ci
    - npm run build
    - cp -r build/client/* public/
  artifacts:
    paths:
      - public
  only:
    - main
