// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/granskning/:id": {
    params: {
      "id": string;
    };
  };
  "/granskning/:id/:reqId": {
    params: {
      "id": string;
      "reqId": string;
    };
  };
  "/granskning/skapa": {
    params: {};
  };
  "/granskning/:id/redigera": {
    params: {
      "id": string;
    };
  };
  "/granskning/:id/underkanda-krav": {
    params: {
      "id": string;
    };
  };
  "/krav": {
    params: {};
  };
  "/tips": {
    params: {};
  };
  "/tillganglighetsredogorelse": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/granskning/:id" | "/granskning/:id/:reqId" | "/granskning/skapa" | "/granskning/:id/redigera" | "/granskning/:id/underkanda-krav" | "/krav" | "/tips" | "/tillganglighetsredogorelse";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/reviewOverview.tsx": {
    id: "review-overview";
    page: "/granskning/:id";
  };
  "routes/review.tsx": {
    id: "review-req";
    page: "/granskning/:id/:reqId";
  };
  "routes/addReview.tsx": {
    id: "routes/addReview";
    page: "/granskning/skapa";
  };
  "routes/editReview.tsx": {
    id: "edit";
    page: "/granskning/:id/redigera";
  };
  "routes/failed.tsx": {
    id: "failed";
    page: "/granskning/:id/underkanda-krav";
  };
  "routes/requirements.tsx": {
    id: "requirements";
    page: "/krav";
  };
  "routes/tips.tsx": {
    id: "tips";
    page: "/tips";
  };
  "routes/accessibilityStatement.tsx": {
    id: "accessibility-statement";
    page: "/tillganglighetsredogorelse";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/home": typeof import("./app/routes/home.tsx");
  "review-overview": typeof import("./app/routes/reviewOverview.tsx");
  "review-req": typeof import("./app/routes/review.tsx");
  "routes/addReview": typeof import("./app/routes/addReview.tsx");
  "edit": typeof import("./app/routes/editReview.tsx");
  "failed": typeof import("./app/routes/failed.tsx");
  "requirements": typeof import("./app/routes/requirements.tsx");
  "tips": typeof import("./app/routes/tips.tsx");
  "accessibility-statement": typeof import("./app/routes/accessibilityStatement.tsx");
};